//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ServiciosAerolinea.AerolineaTWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConsultaPWSPortBinding", Namespace="http://ws.aerolinea.arquitectura.teamj.com/")]
    public partial class ConsultaPWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback consultaPOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConsultaPWS() {
            this.Url = global::ServiciosAerolinea.Properties.Settings.Default.ServiciosAerolinea_AerolineaTWS_ConsultaPWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultaPCompletedEventHandler consultaPCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.aerolinea.arquitectura.teamj.com/", ResponseNamespace="http://ws.aerolinea.arquitectura.teamj.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public consultaPasajeRespuesta[] consultaP([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] consultaPasajePeticion parametrosBusqueda) {
            object[] results = this.Invoke("consultaP", new object[] {
                        parametrosBusqueda});
            return ((consultaPasajeRespuesta[])(results[0]));
        }
        
        /// <remarks/>
        public void consultaPAsync(consultaPasajePeticion parametrosBusqueda) {
            this.consultaPAsync(parametrosBusqueda, null);
        }
        
        /// <remarks/>
        public void consultaPAsync(consultaPasajePeticion parametrosBusqueda, object userState) {
            if ((this.consultaPOperationCompleted == null)) {
                this.consultaPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaPOperationCompleted);
            }
            this.InvokeAsync("consultaP", new object[] {
                        parametrosBusqueda}, this.consultaPOperationCompleted, userState);
        }
        
        private void OnconsultaPOperationCompleted(object arg) {
            if ((this.consultaPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaPCompleted(this, new consultaPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.aerolinea.arquitectura.teamj.com/")]
    public partial class consultaPasajePeticion {
        
        private string destinoField;
        
        private System.DateTime fechaRetornoField;
        
        private bool fechaRetornoFieldSpecified;
        
        private System.DateTime fechaSalidaField;
        
        private bool fechaSalidaFieldSpecified;
        
        private string origenField;
        
        private int totalAsientosField;
        
        private bool totalAsientosFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaRetorno {
            get {
                return this.fechaRetornoField;
            }
            set {
                this.fechaRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRetornoSpecified {
            get {
                return this.fechaRetornoFieldSpecified;
            }
            set {
                this.fechaRetornoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaSalida {
            get {
                return this.fechaSalidaField;
            }
            set {
                this.fechaSalidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSalidaSpecified {
            get {
                return this.fechaSalidaFieldSpecified;
            }
            set {
                this.fechaSalidaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string origen {
            get {
                return this.origenField;
            }
            set {
                this.origenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int totalAsientos {
            get {
                return this.totalAsientosField;
            }
            set {
                this.totalAsientosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalAsientosSpecified {
            get {
                return this.totalAsientosFieldSpecified;
            }
            set {
                this.totalAsientosFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.aerolinea.arquitectura.teamj.com/")]
    public partial class consultaPasajeRespuesta {
        
        private int codigoVueloField;
        
        private bool codigoVueloFieldSpecified;
        
        private decimal costoAsientoField;
        
        private bool costoAsientoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoVuelo {
            get {
                return this.codigoVueloField;
            }
            set {
                this.codigoVueloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoVueloSpecified {
            get {
                return this.codigoVueloFieldSpecified;
            }
            set {
                this.codigoVueloFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal costoAsiento {
            get {
                return this.costoAsientoField;
            }
            set {
                this.costoAsientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool costoAsientoSpecified {
            get {
                return this.costoAsientoFieldSpecified;
            }
            set {
                this.costoAsientoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void consultaPCompletedEventHandler(object sender, consultaPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public consultaPasajeRespuesta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((consultaPasajeRespuesta[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591